FROM sentiox/openwrt-sdk-apk:25.12.3

ARG HARPYNET_VERSION
ENV HARPYNET_VERSION=${HARPYNET_VERSION}

COPY ./harpynet /builder/package/feeds/utilities/harpynet
COPY ./luci-app-harpynet /builder/package/feeds/luci/luci-app-harpynet

RUN make defconfig && \
    make package/harpynet/compile -j4 V=s && \
    make package/luci-app-harpynet/compile -j4 V=s