FROM openwrt/sdk:x86_64-v25.12.3

WORKDIR /builder

RUN ./setup.sh && \
    ./scripts/feeds update -a && \
    ./scripts/feeds install luci-base && \
    mkdir -p /builder/package/feeds/utilities/ && \
    mkdir -p /builder/package/feeds/luci/

ARG HARPYNET_VERSION
ENV HARPYNET_VERSION=${HARPYNET_VERSION}

COPY ./harpynet /builder/package/feeds/utilities/harpynet
COPY ./luci-app-harpynet /builder/package/feeds/luci/luci-app-harpynet

RUN make defconfig && \
    make package/harpynet/compile -j4 V=s && \
    make package/luci-app-harpynet/compile -j4 V=s
